services:
  # PostgreSQL database for TinySphere
  postgres:
    image: postgres:14
    container_name: tinysphere-postgres
    environment:
      POSTGRES_USER: tinysphere
      POSTGRES_PASSWORD: tinysphere
      POSTGRES_DB: tinysphere
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tinysphere-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tinysphere"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL database for MLflow
  mlflow-postgres:
    image: postgres:14
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    volumes:
      - mlflow-postgres-data:/var/lib/postgresql/data
    networks:
      - tinysphere-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO S3-compatible storage for artifacts
  minio:
    image: minio/minio:latest
    container_name: tinysphere-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # Allow iframe embedding
      MINIO_BROWSER_SECURE_FRAMING: "false"
      MINIO_BROWSER_REDIRECT_ALLOW_HOSTS: "*"
      MINIO_BROWSER: "on"
      # CORS settings
      MINIO_CORS_ALLOW_ORIGIN: "*"
      MINIO_CORS_ALLOW_METHODS: "GET,PUT,POST,DELETE,OPTIONS"
      MINIO_CORS_ALLOW_HEADERS: "Accept,Authorization,Content-Type,Content-Length,X-Amz-Date,X-Amz-Content-SHA256,X-Amz-Security-Token,X-Requested-With"
      MINIO_CORS_EXPOSE_HEADERS: "ETag,X-Amz-Meta-*"
      # Security headers customization
      MINIO_BROWSER_CONTENT_SECURITY_POLICY: "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: http: https:; frame-ancestors 'self' *;"
      MINIO_BROWSER_STRICT_TRANSPORT_SECURITY: "max-age=31536000;"
      MINIO_BROWSER_X_FRAME_OPTIONS: "ALLOWALL"
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - tinysphere-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MinIO setup service to create buckets
  minio-setup:
    image: minio/mc:latest
    container_name: tinysphere-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/mlflow;
      /usr/bin/mc policy set download minio/mlflow;
      /usr/bin/mc mb minio/drift;
      /usr/bin/mc mb minio/drift-samples;
      /usr/bin/mc mb minio/drift-features;
      /usr/bin/mc mb minio/prediction-images;
      /usr/bin/mc mb minio/data-logs;
      /usr/bin/mc policy set download minio/drift;
      /usr/bin/mc policy set download minio/drift-samples;
      /usr/bin/mc policy set download minio/drift-features;
      /usr/bin/mc policy set download minio/prediction-images;
      /usr/bin/mc policy set download minio/data-logs;
      exit 0;
      "
    networks:
      - tinysphere-network

  # MLflow tracking server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    container_name: tinysphere-mlflow
    depends_on:
      mlflow-postgres:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    command: >
      bash -c "pip install psycopg2-binary boto3 alembic && 
      mlflow server 
      --backend-store-uri postgresql://mlflow:mlflow@mlflow-postgres:5432/mlflow 
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    ports:
      - "5001:5000"
    networks:
      - tinysphere-network

  # TinySphere API service
  tinysphere-api:
    build:
      context: .
      dockerfile: tinysphere/docker/Dockerfile.backend
    container_name: tinysphere-api
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://tinysphere:tinysphere@postgres:5432/tinysphere
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_SECURE: "False"
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app/tinylcm:/app  # Wichtig für Imports
    ports:
      - "8000:8000"
    networks:
      - tinysphere-network
    volumes:
      - ./tinysphere/api:/app/tinysphere/api
      - ./tinysphere/db:/app/tinysphere/db
      - ./tinysphere/importer:/app/tinysphere/importer
      - ./tinysphere/requirements.txt:/app/requirements.txt
      - ./tinylcm:/app/tinylcm  # Für Development
      - ./uploads:/app/uploads
      
  tinysphere-frontend:
    build:
      context: .
      dockerfile: tinysphere/docker/Dockerfile.frontend
    container_name: tinysphere-frontend
    ports:
      - "3000:80"
    depends_on:
      tinysphere-api:
        condition: service_started
    restart: unless-stopped
    networks:
      - tinysphere-network

networks:
  tinysphere-network:
    driver: bridge

volumes:
  postgres-data:
  mlflow-postgres-data:
  minio-data: